# -*- coding: utf-8 -*-
"""Customer churn analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z15z1crRNufr2DKl8i0YE6CFRN2G-i8A
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sns.set()
np.random.seed(42)

n = 100000

data = pd.DataFrame({
    "Customer_ID": np.arange(1, n+1),
    "Age": np.random.randint(18, 70, n),
    "Gender": np.random.choice(["Male", "Female"], n),
    "Tenure": np.random.randint(0, 11, n),
    "Balance": np.random.randint(0, 200000, n),
    "CreditScore": np.random.randint(300, 900, n),
    "EstimatedSalary": np.random.randint(10000, 150000, n),
    "NumOfProducts": np.random.randint(1, 5, n),
    "IsActiveMember": np.random.choice(["Yes", "No"], n),
    "Churn": np.random.choice([0, 1], n, p=[0.7, 0.3])
})

data.head()

print(data.isnull().sum())
data['Gender'] = data['Gender'].map({'Male': 0, 'Female': 1})
data['IsActiveMember'] = data['IsActiveMember'].map({'No': 0, 'Yes': 1})

data.info()

print(data.describe())

print(data['Churn'].value_counts())

sns.countplot(x='Churn', data=data)
plt.title("Churn Distribution")
plt.show()

sns.boxplot(x='Churn', y='Age', data=data)
plt.title("Age vs Churn")
plt.show()

sns.boxplot(x='Churn', y='Balance', data=data)
plt.title("Balance vs Churn")
plt.show()

sns.countplot(x='IsActiveMember', hue='Churn', data=data)
plt.title("Active Member vs Churn")
plt.show()

sns.countplot(x='IsActiveMember', hue='Churn', data=data)
plt.title("Active Member vs Churn")
plt.show()

sns.countplot(x='NumOfProducts', hue='Churn', data=data)
plt.title("Products vs Churn")
plt.show()

plt.figure(figsize=(10,6))
sns.heatmap(data.corr(), annot=True, cmap='coolwarm')
plt.title("Correlation Heatmap")
plt.show()

print("\nTop Customers:")
print(data.sort_values(by="Balance", ascending=False).head())

